// Package stock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package stock

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Message string `json:"message"`
}

// NewStockItem defines model for NewStockItem.
type NewStockItem = StockItemName

// StockItem defines model for StockItem.
type StockItem struct {
	Id   openapi_types.UUID `json:"id" validate:"required"`
	Name string             `json:"name" validate:"required,lt=100"`
}

// StockItemId defines model for StockItemId.
type StockItemId struct {
	Id openapi_types.UUID `json:"id" validate:"required"`
}

// StockItemName defines model for StockItemName.
type StockItemName struct {
	Name string `json:"name" validate:"required,lt=100"`
}

// BadRequest defines model for BadRequest.
type BadRequest = BadRequestResponse

// Created defines model for Created.
type Created = StockItem

// OK defines model for OK.
type OK = StockItem

// PostStockItemJSONRequestBody defines body for PostStockItem for application/json ContentType.
type PostStockItemJSONRequestBody = NewStockItem

// PutStockItemJSONRequestBody defines body for PutStockItem for application/json ContentType.
type PutStockItemJSONRequestBody = NewStockItem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Stock Item
	// (POST /stock/items)
	PostStockItem(ctx echo.Context) error
	// Delete Stock Item
	// (DELETE /stock/items/{stockitemId})
	DeleteStockItem(ctx echo.Context, stockitemId openapi_types.UUID) error
	// Update Stock Item
	// (PUT /stock/items/{stockitemId})
	PutStockItem(ctx echo.Context, stockitemId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) PostStockItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStockItem(ctx)
	return err
}

// DeleteStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStockItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "stockitemId" -------------
	var stockitemId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "stockitemId", runtime.ParamLocationPath, ctx.Param("stockitemId"), &stockitemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter stockitemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStockItem(ctx, stockitemId)
	return err
}

// PutStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) PutStockItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "stockitemId" -------------
	var stockitemId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "stockitemId", runtime.ParamLocationPath, ctx.Param("stockitemId"), &stockitemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter stockitemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutStockItem(ctx, stockitemId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/stock/items", wrapper.PostStockItem)
	router.DELETE(baseURL+"/stock/items/:stockitemId", wrapper.DeleteStockItem)
	router.PUT(baseURL+"/stock/items/:stockitemId", wrapper.PutStockItem)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVTW/bMAz9Kwa3oxI7a3cxsMO6DyAo0BYtdip6EGwm1WZ9VKK7BIH++yA5H3acJSka",
	"rLtFFPX4/B7JLKDQ0miFihzkC7DojFYO4+GCl7f4VKOjcCq0IlTxJzemEgUnoVX602kVYq54RMnDr/cW",
	"J5DDu3QDnTa3Lt1A3i4rgfeeQYmusMIERMhD4WRV2TP4YpETlicjcUe6+DUmlLtqr4p5BmNFaBWv7tA+",
	"o/1mrbYBupu/SkqarKRJ8wyuNH3XtSr7T640Jc2VZ3B9+W++6/oSQnCZ27V37UW+AGO1QUuiaQGJzvFp",
	"vKC5QcjBkRVqGrEsPtXCBmPu14kP4cvx94ZK+KKqup5Afn8k+ysuEXwAeg3KOKi7P7fDs1twXPa1EDE2",
	"0VZyghzqWpTAtmRhMBtobsSg0CVOUQ1wRpYPiE8jxDOvRMkpPFiL57elFCV0uEQ9emzUMir5TMhaQj7K",
	"MgZSqOXp9cxYRZ9GWdYnGEs/xLBQEx2bQ1AV3kbSSWCdfL4ZA4NntK5pwNEwG2ah47VBxY2AHM6G2fAM",
	"GBhOj5FF6sL7VBDKeDa62T27RjTZ1IIIauPMBOfgRjvaWNuwR0cXupyfbNq63dPViGyNMdDaph+y0d8g",
	"13lpa/ucZ9nh/NaK9gw+HvNk11aLm6GWktv5Tn3DfdubdBEPIk6KbxyqkLDv1dcY3+dVk9F2y3DLJRJa",
	"F8ddBJzQIsCWXQ+t6rCtO2v5t39YvX/oeXSEgGGTBnvOD6eu/wNOZ05fUM/A1DvG5IcpD41JTW+o+/8w",
	"ki+w+8XT+FYd0vfde+//BAAA//+yRQdE6gkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
